[package]
name = "datafusion-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

arrow = "9"
aws-sdk-s3 = "0.6.0"
aws-types = "0.6.0"
# ballista = {version = "0.6", optional=true}
clap = {version = "3", features = ["derive", "cargo"]}
crossterm = { version = "0.23", features = [ "serde" ] }
datafusion = "7"
datafusion-objectstore-s3 = { version = "0", optional=true }
datafusion-objectstore-azure = { git = "https://github.com/datafusion-contrib/datafusion-objectstore-azure", branch="main", optional=true }
datafusion-bigtable = { version = "0", optional=true }
dirs = "4.0"
futures = "0.3"
http = "0.2.6"
log = "0.4"
mimalloc = { version = "*", default-features = false }
serde = "1.0.136"
serde_json = "1.0.79"
tui = { version = "0.17", default-features = false, features = ['crossterm', 'serde'] }
tui-logger = "0.7"
tokio = { version = "1", features = ["full"] }
unicode-width = "0.1.9"

[features]
s3 = ["datafusion-objectstore-s3"]
bigtable = ["datafusion-bigtable"]
azure = ["datafusion-objectstore-azure"]
# ballista = ["ballista"]